### ISSUE TITLE
Assessment period not consistently used in code

### ISSUE THREAD

**Issue by kcollingridge** [ices-tools-prod/COMPEAT#13]
I was a bit puzzled why some of my plots came out with one assessment period in the title and some with another though they were run on the same data. Looking through the code it is because some take this from "assessmentPeriod" as defined early on the in the script and some from "indicatorYearMin" and "indicatorYearMax". I would expect these to be the same but they are not necessarily. The function download.file.unzip.maybe checks to see if data has already been downloaded and saved and if it has, does not do so again. However it does not check which assessment period the data has been downloaded for. So if the first time you run it for 2015-2020 it will download that data, then if you try to run again for 2006-2014 it will use the same data you already downloaded which is not for the right time period. I haven't yet fixed this issue, I guess the best solution would be to edit  download.file.unzip.maybe to check which version of StationSamples.txt.gz is saved?

**Comment by HjalteParner** [comment]
Noted Kate. I get your point and agree that it should be done only one place. I will look into a better solution for this as soon as I have some time.

**Comment by HjalteParner** [comment]
@kcollingridge I think this issue is solved now. On the longer term I might create one large file for 1990-2020 which can be used for all COMP assessment periods and the trend assessment using TTA for that matter.
